language: node_js
arch:
  - amd64
  - ppc64le
after_success: npm run coverage && cat ./coverage/lcov.info | coveralls
script:
  - npm run pretest
  - npm run $CMD
cache:
  npm: false
matrix:
  include:
    - node_js: 10
      env: CMD=test-node
    - node_js: 10
      env: CMD=test-262
    - node_js: 10
      env: CMD=test-browser
    - node_js: 10
      env: CMD=test-website
  fast_finish: true
sudo: false
